export * from "./types";

export {
  base64UrlEncode,
  base64UrlDecode,
  generateRandomString,
  extractAuthResults,
  sanitizeUrl,
  generateAuthUrl,
  mapLoginMethodParamsForUrl,
  exchangeAuthCode,
  checkAuth,
  isCustomDomain,
  setRefreshTimer,
  clearRefreshTimer,
  frameworkSettings,
  splitString,
  generateProfileUrl,
  generatePortalUrl,
  generateKindeSDKHeader,
  navigateToKinde,
  updateActivityTimestamp,
  sessionManagerActivityProxy,
  isClient,
  isServer,
  switchOrg,
} from "./utils";

export {
  getClaim,
  getClaimSync,
  getClaims,
  getClaimsSync,
  getCurrentOrganization,
  getCurrentOrganizationSync,
  getRawToken,
  getRawTokenSync,
  getDecodedToken,
  getDecodedTokenSync,
  getFlag,
  getFlagSync,
  getUserProfile,
  getUserProfileSync,
  getPermission,
  getPermissionSync,
  getEntitlement,
  getEntitlements,
  getPermissions,
  getPermissionsSync,
  getUserOrganizations,
  getUserOrganizationsSync,
  getRoles,
  getRolesSync,
  isAuthenticated,
  isTokenExpired,
  refreshToken,
  setActiveStorage,
  getActiveStorage,
  hasActiveStorage,
  clearActiveStorage,
  setInsecureStorage,
  getInsecureStorage,
  hasInsecureStorage,
  clearInsecureStorage,
  has,
  hasPermissions,
  hasRoles,
  hasFeatureFlags,
  hasBillingEntitlements,
} from "./utils/token";

export type {
  UserProfile,
  Permissions,
  Role,
  PermissionAccess,
} from "./utils/token";

export {
  storageSettings,
  MemoryStorage,
  ChromeStore,
  LocalStorage,
  StorageKeys,
  SessionBase,
  TimeoutActivityType,
} from "./sessionManager";

export type { SessionManager, TimeoutTokenData } from "./sessionManager";
